#!/usr/bin/env bash
#To file, or not to file
filename="school"
if [ -e "$filename" ]; then
echo "school file exists "
else
echo "school file does not exist"
fi
if [ -s "$filename"]; then
echo "school file is empty"
else
echo"school file is not empty"
fi
if [ -f "$filename"]; then
echo "school file is a regular file"
else
echo"nothing"
fi
